/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment2;

import javax.swing.*;
import java.util.Random;

/**
 *
 * @author lenovo
 */
public class AssignmentJFrame extends javax.swing.JFrame {

    private RubikClock game;

    /**
     * Creates new form AssignmentJFrame
     */
    private javax.swing.JLabel[] clocks;
    private int[] clockHours = new int[9];
    ; // Array to hold clock hours
    private int steps = 0; // Step counter

    public AssignmentJFrame() {
        initComponents();
        game = new RubikClock();
        updateClocksDisplay();
    }

    private void updateClocksDisplay() {
        int[] clockHours = game.getClockHours();
        clock1.setText("Clock1: " + clockHours[0]);
        clock2.setText("Clock2: " + clockHours[1]);
        clock3.setText("Clock3: " + clockHours[2]);
        clock4.setText("Clock4: " + clockHours[3]);
        clock5.setText("Clock5: " + clockHours[4]);
        clock6.setText("Clock6: " + clockHours[5]);
        clock7.setText("Clock7: " + clockHours[6]);
        clock8.setText("Clock8: " + clockHours[7]);
        clock9.setText("Clock9: " + clockHours[8]);
    }

    private void onGameWon() {
      
      JOptionPane.showMessageDialog(this, "You won in " + game.getSteps() + " steps!");
        game.setupSolvableState();
        updateClocksDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        clock1 = new javax.swing.JLabel();
        clock2 = new javax.swing.JLabel();
        clock3 = new javax.swing.JLabel();
        clock4 = new javax.swing.JLabel();
        clock5 = new javax.swing.JLabel();
        clock6 = new javax.swing.JLabel();
        clock7 = new javax.swing.JLabel();
        clock8 = new javax.swing.JLabel();
        clock9 = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        restart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        clock1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        clock1.setText("Clock1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 116, 0, 0);
        getContentPane().add(clock1, gridBagConstraints);

        clock2.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        clock2.setText("Clock2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 0, 0, 0);
        getContentPane().add(clock2, gridBagConstraints);

        clock3.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        clock3.setText("Clock3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 39, 0, 0);
        getContentPane().add(clock3, gridBagConstraints);

        clock4.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        clock4.setText("Clock4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 116, 0, 0);
        getContentPane().add(clock4, gridBagConstraints);

        clock5.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        clock5.setText("Clock5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        getContentPane().add(clock5, gridBagConstraints);

        clock6.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        clock6.setText("Clock6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 39, 0, 81);
        getContentPane().add(clock6, gridBagConstraints);

        clock7.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        clock7.setText("Clock7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 116, 0, 0);
        getContentPane().add(clock7, gridBagConstraints);

        clock8.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        clock8.setText("Clock8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 1, 0, 0);
        getContentPane().add(clock8, gridBagConstraints);

        clock9.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        clock9.setText("Clock9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 39, 0, 0);
        getContentPane().add(clock9, gridBagConstraints);

        button1.setBackground(new java.awt.Color(51, 204, 0));
        button1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button1.setText("Click");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 154, 0, 0);
        getContentPane().add(button1, gridBagConstraints);

        button2.setBackground(new java.awt.Color(51, 204, 0));
        button2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button2.setText("Click");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 47, 0, 0);
        getContentPane().add(button2, gridBagConstraints);

        button3.setBackground(new java.awt.Color(0, 204, 0));
        button3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button3.setText("Click");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 153, 0, 0);
        getContentPane().add(button3, gridBagConstraints);

        button4.setBackground(new java.awt.Color(0, 204, 0));
        button4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button4.setText("Click");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 48, 0, 0);
        getContentPane().add(button4, gridBagConstraints);

        restart.setBackground(new java.awt.Color(255, 255, 0));
        restart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        restart.setText("Restart");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 39, 128, 0);
        getContentPane().add(restart, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rubik Clock");
        jLabel1.setMaximumSize(new java.awt.Dimension(85, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(74, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.ipadx = 288;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 64, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        game.incrementClockHours(0);
        updateClocksDisplay();
        if (game.checkWinCondition()) {
            onGameWon();
        }

    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        game.incrementClockHours(1);
        updateClocksDisplay();
        if (game.checkWinCondition()) {
            onGameWon();
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        game.incrementClockHours(2);
        updateClocksDisplay();
        if (game.checkWinCondition()) {
            onGameWon();
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        game.incrementClockHours(3);
        updateClocksDisplay();
        if (game.checkWinCondition()) {
            onGameWon();
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        game.setupSolvableState();
        updateClocksDisplay();
    }//GEN-LAST:event_restartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignmentJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JLabel clock1;
    private javax.swing.JLabel clock2;
    private javax.swing.JLabel clock3;
    private javax.swing.JLabel clock4;
    private javax.swing.JLabel clock5;
    private javax.swing.JLabel clock6;
    private javax.swing.JLabel clock7;
    private javax.swing.JLabel clock8;
    private javax.swing.JLabel clock9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton restart;
    // End of variables declaration//GEN-END:variables
}
